export const TELEMETRY_CONTROLLER_REGISTRY = {
  POWERTRAIN: Symbol.for(
    'MODULE::APPLICATION::CONTROLLER::TELEMETRY::POWERTRAIN',
  ),
  BATTERY: Symbol.for('MODULE::APPLICATION::CONTROLLER::TELEMETRY::BATTERY'),
};
