export const TELEMETRY_SERVICE_REGISTRY = {
  POWERTRAIN: Symbol.for('MODULE::APPLICATION::SERVICE::TELEMETRY::POWERTRAIN'),
  BATTERY: Symbol.for('MODULE::APPLICATION::SERVICE::TELEMETRY::BATTERY'),
  GEOGRAPHY: Symbol.for('MODULE::APPLICATION::SERVICE::TELEMETRY::GEOGRAPHY'),
  GYROSCOPE: Symbol.for('MODULE::APPLICATION::SERVICE::TELEMETRY::GYROSCOPE'),
};
