import { SERIAL_TELEMETRY_GATEWAY_REGISTRY } from './telemetry/telemetry.registy';

export const SERIAL_GATEWAY_REGISTRY = {
  SERIAL_PORT: Symbol('MODULE::APPLICATION::GATEWEAY::SERIAL'),
  TELEMETRY: SERIAL_TELEMETRY_GATEWAY_REGISTRY,
};
