export const HTTP_SERVER_REGISTRY = {
  EXPRESS: {
    APP: Symbol.for('MODULE::INFRA::ENGINE::SERVER::HTTP::EXPRESS'),
    CORS: Symbol.for('MODULE::INFRA::ENGINE::SERVER::HTTP::EXPRESS::CORS'),
    ROUTER: Symbol.for('MODULE::INFRA::ENGINE::SERVER::HTTP::EXPRESS::ROUTER'),
    PARSER: {
      BODY: Symbol.for(
        'MODULE::INFRA::ENGINE::SERVER::HTTP::EXPRESS::BODY_PARSER',
      ),
    },
  },
};
