import 'reflect-metadata';

import { MODULES } from './@module/app.factory';

const APP = MODULES.INFRA.SERVER.HTTP.EXPRESS.APP();

APP.use(MODULES.INFRA.SERVER.HTTP.EXPRESS.CORS());
APP.use(MODULES.INFRA.SERVER.HTTP.EXPRESS.PARSER.BODY());
APP.use(MODULES.APPLICATION.MIDDLEWARE.HTTP.EXPRESS.LOGGER.APP());
APP.use(MODULES.APPLICATION.ROUTER.HTTP.EXPRESS.APP());
APP.use(MODULES.APPLICATION.ROUTER.HTTP.EXPRESS.DOCS());
APP.use(MODULES.APPLICATION.ROUTER.HTTP.EXPRESS.TELEMETRY.POWERTRAIN());
APP.use(MODULES.APPLICATION.MIDDLEWARE.HTTP.EXPRESS.LOGGER.ERROR());
APP.use(MODULES.APPLICATION.MIDDLEWARE.HTTP.EXPRESS.ERROR());

export { APP };
